linter:
  rules:
    # STYLE
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names # prefer
    - directives_ordering
    - lines_longer_than_80_chars # avoid
    - curly_braces_in_flow_control_structures

    # USAGE
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - implementation_imports
    - avoid_relative_lib_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps # avoid
    - prefer_collection_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - no_duplicate_case_values
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - null_closures
    - unnecessary_getters_setters
    - prefer_expression_function_bodies # consider
    - unnecessary_this
    - unrelated_type_equality_checks
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - unawaited_futures
    - recursive_getters
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - use_rethrow_when_possible

    # DESIGN
    - avoid_empty_else
    - avoid_types_as_parameter_names
    - empty_catches
    - use_to_and_as_if_applicable # prefer
    - one_member_abstracts # avoid
    - avoid_classes_with_only_static_members
    - prefer_mixin
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_single_quotes
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_null
    - avoid_returning_this
    - prefer_typing_uninitialized_variables
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_if_null_operators
    - prefer_spread_collections
    - omit_local_variable_types # avoid
    - avoid_types_on_closure_parameters
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions # prefer
    - use_function_type_syntax_for_parameters # consider
    - unnecessary_null_in_if_null_operators
    - avoid_positional_boolean_parameters
    - hash_and_equals
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_null_checks_in_equality_operators